# Generated by Django 5.1 on 2024-10-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField()),
                ('is_accepted', models.BooleanField(default=False, help_text='Designates whether this feedback is displayed in index', verbose_name='active')),
                ('permission_to_display', models.BooleanField(default=False)),
            ],
        ),
    ]
