# Generated by Django 5.1 on 2024-09-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Designates whether this feedback is displayed in index', verbose_name='active'),
        ),
    ]
