# Generated by Django 5.1 on 2024-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0002_alter_hero_logo_alter_hero_site_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='image_url'),
        ),
    ]
