# Generated by Django 5.1 on 2024-10-16 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateTimeField()),
                ('signup_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sign up date')),
                ('bamboo', models.BooleanField(default=False)),
                ('vegetables', models.BooleanField(default=False)),
                ('eggs', models.BooleanField(default=False)),
                ('shiitake', models.BooleanField(default=False)),
                ('bees', models.BooleanField(default=False)),
                ('goats', models.BooleanField(default=False)),
                ('construction', models.BooleanField(default=False)),
                ('restrictions', models.TextField(blank=True, default=None, null=True)),
                ('is_regular_volunteer', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False, help_text='Designates whether this volunteer is accepted. Review then accept', verbose_name='active')),
            ],
        ),
    ]
