# Generated by Django 5.1 on 2024-08-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_volunteer_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='restrictions',
            field=models.TextField(null=True),
        ),
    ]
