# Generated by Django 5.1 on 2024-09-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_remove_volunteer_status_volunteer_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Designates whether this volunteer is accepted. Review then accept', verbose_name='active'),
        ),
    ]
