# Generated by Django 5.1 on 2024-09-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_alter_volunteer_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='category',
            field=models.IntegerField(help_text='1-Weeds, 2-Shittake Mushrooms, 3-Eggs, 4-Bee Keeping, 5-Bamboo', null=True),
        ),
    ]
