# Generated by Django 5.1 on 2024-09-02 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_alter_volunteer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='signup_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='sign up date'),
        ),
    ]
