# Generated by Django 5.1 on 2024-09-02 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('volunteers', '0008_alter_volunteer_signup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
