# Generated by Django 5.1 on 2024-09-02 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_remove_volunteer_category_volunteer_bamboo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='signup_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='sign up date'),
        ),
    ]
