# Generated by Django 5.1 on 2024-09-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_alter_volunteer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='category',
        ),
    ]
