# Generated by Django 4.2.15 on 2024-09-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0012_alter_volunteer_signup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='one_time_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='regular_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
