# Generated by Django 4.2.15 on 2024-09-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0013_volunteer_one_time_volunteer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='regular_volunteer',
            new_name='is_regular_volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='one_time_volunteer',
        ),
    ]
