# Generated by Django 5.1 on 2024-08-27 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_desc', models.TextField()),
                ('link', models.TextField()),
                ('img_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.media')),
            ],
        ),
    ]
