# Generated by Django 4.2.16 on 2024-11-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(default='title', max_length=100)),
                ('card_desc', models.TextField(default='description')),
                ('link', models.TextField(default='link')),
                ('img_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medias.media')),
            ],
        ),
    ]
