# Generated by Django 5.1 on 2024-09-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='card_title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
