# Generated by Django 5.1 on 2024-08-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.media'),
        ),
    ]
