# Generated by Django 5.1 on 2024-09-05 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_text_blog_blog_rename_name_blog_title_and_more'),
        ('medias', '0002_alter_media_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.AddField(
            model_name='blog',
            name='img_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.media'),
        ),
    ]
