# Generated by Django 5.1 on 2024-09-08 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_img_url'),
        ('medias', '0016_media_alt_text_media_set_as_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_url',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='medias.media'),
            preserve_default=False,
        ),
    ]
