# Generated by Django 4.2.16 on 2024-11-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_img', models.BinaryField(default=b'', null=True)),
                ('set_as_hero', models.BooleanField(default=False)),
                ('alt_text', models.CharField(default='image', max_length=150)),
            ],
        ),
    ]
