# Generated by Django 5.1 on 2024-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='img_url',
            field=models.ImageField(default='default.jpg', upload_to='image_url'),
        ),
    ]
