# Generated by Django 5.1 on 2024-09-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_media_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='img_url',
            new_name='imageUrl',
        ),
        migrations.AddField(
            model_name='media',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
