# Generated by Django 5.1 on 2024-09-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_media_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', models.TextField(blank=True, db_column='data')),
            ],
        ),
        migrations.RenameField(
            model_name='media',
            old_name='img_url',
            new_name='imageUrl',
        ),
        migrations.AddField(
            model_name='media',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
