# Generated by Django 5.1 on 2024-09-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_filedata_foo_rename_img_url_media_imageurl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileData',
        ),
        migrations.AddField(
            model_name='media',
            name='data',
            field=models.BinaryField(null=True),
        ),
    ]
