# Generated by Django 5.1 on 2024-09-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_delete_filedata_media_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foo',
            new_name='Data',
        ),
    ]
