# Generated by Django 5.1 on 2024-09-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_rename_foo_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='media',
            name='data',
        ),
        migrations.RemoveField(
            model_name='media',
            name='date_created',
        ),
        migrations.AddField(
            model_name='media',
            name='image_b64',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='imageUrl',
            field=models.ImageField(default='blank.jpg', upload_to='images/'),
        ),
    ]
