# Generated by Django 5.1 on 2024-09-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0006_delete_data_remove_media_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='imageUrl',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_b64',
            field=models.TextField(null=True),
        ),
    ]
