# Generated by Django 5.1 on 2024-09-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0008_alter_media_image_b64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='imageUrl',
        ),
        migrations.AlterField(
            model_name='media',
            name='image_b64',
            field=models.BinaryField(default=None),
        ),
    ]
