# Generated by Django 5.1 on 2024-09-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0011_remove_media_image_b64'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='blob_img',
            field=models.BinaryField(default=b'', null=True),
        ),
    ]
