# Generated by Django 5.1 on 2024-09-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0012_media_blob_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
