# Generated by Django 5.1 on 2024-09-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0013_media_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='img_data',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
