# Generated by Django 5.1 on 2024-09-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0014_remove_media_image_media_img_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='img_data',
        ),
    ]
