# Generated by Django 5.1 on 2024-09-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0015_remove_media_img_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt_text',
            field=models.CharField(default='image', max_length=150),
        ),
        migrations.AddField(
            model_name='media',
            name='set_as_hero',
            field=models.BooleanField(default=False),
        ),
    ]
